### ISSUE TITLE
ReferenceError: "retVal" is not defined

### ISSUE THREAD

**Issue by kyle1970** [qiujiayu/AutoLoadCache#19]
我使用jdk8,autoload-cache:4.16,JavaScriptParser，jsel表达式时候出现一个问题
1、在使用@Cache(expire=300, key="retVal.userName", condition="args[0]>0")时候报错：
javax.script.ScriptException: ReferenceError: "retVal" is not defined in <eval> at line number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:455) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:416) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.access$300(NashornScriptEngine.java:70) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine$3.eval(NashornScriptEngine.java:499) ~[nashorn.jar:na]
	at javax.script.CompiledScript.eval(CompiledScript.java:92) ~[na:1.8.0_51]
	at com.jarvis.cache.script.JavaScriptParser.getElValue(JavaScriptParser.java:87) ~[autoload-cache-4.16.jar:na]
	at com.jarvis.cache.script.AbstractScriptParser.getDefinedCacheKey(AbstractScriptParser.java:67) ~[autoload-cache-4.16.jar:na]
	at com.jarvis.cache.AbstractCacheManager.getCacheKey(AbstractCacheManager.java:254) [autoload-cache-4.16.jar:na]
	at com.jarvis.cache.AbstractCacheManager.getCacheKey(AbstractCacheManager.java:283) [autoload-cache-4.16.jar:na]
	at com.jarvis.cache.AbstractCacheManager.proceed(AbstractCacheManager.java:95) [autoload-cache-4.16.jar:na]
	at com.jarvis.cache.aop.nutz.AutoLoadCacheAopInterceptor.filter(AutoLoadCacheAopInterceptor.java:42) [autoload-cache-nutz-4.11.jar:na]
	at org.nutz.aop.InterceptorChain.doChain(InterceptorChain.java:60) [nutz-1.r.57.jar:na]
	at flow.core.dao.UserDao$$NUTZAOP.getById(UserDao.java:1) [nutz-1.r.57.jar:na]

2、但是我改成写模式就能正确返回retVal
@Cache(expire=300, key="retVal.userName",opType=CacheOpType.WRITE, condition="args[0]>0")
这种写模式不会报错，但是在读写模式情况下会抛错

**Comment by qiujiayu** [comment]
在读写模式下，不能使用获取retVal作为缓存key。
[https://github.com/qiujiayu/AutoLoadCache/blob/master/doc/script.md](https://github.com/qiujiayu/AutoLoadCache/blob/master/doc/script.md)
retVal只有以下几中情况才能获得到：方法执行后的返回值（仅当方法执行之后才有效，如@Cache(opType=CacheOpType.WRITE),expireExpression,autoloadCondition,@ExCache()
