### ISSUE TITLE
怀疑 exCache 中配置的hfield不起作用,

### ISSUE THREAD

**Issue by ming300** [qiujiayu/AutoLoadCache#21]
版本 4.16 ,使用map方式存储

配置信息 
```
 @Cache(expire = DateEx.SECOND_ONE_HOUR,
    autoload = false, key = "'SysUserServiceImpl_byName'",
    hfield = "#retVal.userName", condition = "#args.length>0",
    exCache = {@ExCache(
            expire = DateEx.SECOND_ONE_HOUR,
            key = "'SysUserServiceImpl_bypk'",
            hfield = "#retVal.rid")})
    public ConsUser findByLoginName(String userName) 
```

目前报错情况下的数据结构,因此会怀疑 ExCache 未成功支持hfield 
![image](https://cloud.githubusercontent.com/assets/836421/19297596/21ff9eb2-9079-11e6-8904-5033c371c227.png)

正常情况下hfield 起作用的数据结构
![image](https://cloud.githubusercontent.com/assets/836421/19297586/0e33effa-9079-11e6-8071-85706e1cdb73.png)

出错日志
```
123652056;java.lang.ref.SoftReference cannot be cast to java.util.concurrent.ConcurrentHashMap com.jarvis.cache.AbstractCacheManager.writeCache(AbstractCacheManager.java:227)[ERROR]http-bio-8080-exec-24 com.jarvis.cache.AbstractCacheManager {} 165318
java.lang.ClassCastException: java.lang.ref.SoftReference cannot be cast to java.util.concurrent.ConcurrentHashMap
	at com.jarvis.cache.map.CachePointCut.setCache(CachePointCut.java:103)
	at com.jarvis.cache.AbstractCacheManager.writeCache(AbstractCacheManager.java:221)
	at com.jarvis.cache.AbstractCacheManager.proceed(AbstractCacheManager.java:124)
	at com.jarvis.cache.aop.aspectj.AspectjAopInterceptor.proceed(AspectjAopInterceptor.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
```

**Comment by ming300** [comment]
使用下面这套配置信息就是正常的,单独一个方法做注解或者两个方法都做注解都正常.

![image](https://cloud.githubusercontent.com/assets/836421/19298468/6bf5e844-9080-11e6-968e-f9365aac497b.png)

```
 @Cache(expire =DateEx.SECOND_ONE_HOUR,
            autoload = false, key = "'SysUserServiceImpl_bypk'",
            hfield = "#args[0]", condition = "#args.length>0",
            exCache = {@ExCache(
                    expire =DateEx.SECOND_ONE_HOUR,
                    key = "'SysUserServiceImpl_byName'",
                    hfield = "#retVal.userName",condition="#retVal.userName!=null")})
    public ConsUser findByPk(String id) {
    }


    @Cache(expire = DateEx.SECOND_ONE_HOUR,
    autoload = false, key = "'SysUserServiceImpl_byName'",
    hfield = "#args[0]", condition = "#args.length>0",
    exCache = {@ExCache(
            expire = DateEx.SECOND_ONE_HOUR,
            key = "'SysUserServiceImpl_bypk'",
            hfield = "#retVal.rid")})
    public ConsUser findByLoginName(String userName) {

    }
```

上面配置错误的原因为: 
```
hfield = "#retVal.userName" 这个不能够用 #retVal 的值.
```

**Comment by ming300** [comment]
很遗憾,异常继续,
```
170543047;java.lang.ref.SoftReference cannot be cast to java.util.concurrent.ConcurrentHashMap com.jarvis.cache.AbstractCacheManager.writeCache(AbstractCacheManager.java:227)[ERROR]http-bio-8080-exec-5 com.jarvis.cache.AbstractCacheManager {} 669833
java.lang.ClassCastException: java.lang.ref.SoftReference cannot be cast to java.util.concurrent.ConcurrentHashMap
	at com.jarvis.cache.map.CachePointCut.setCache(CachePointCut.java:103)
	at com.jarvis.cache.AbstractCacheManager.writeCache(AbstractCacheManager.java:221)
	at com.jarvis.cache.AbstractCacheManager.proceed(AbstractCacheManager.java:124)
	at com.jarvis.cache.aop.aspectj.AspectjAopInterceptor.proceed(AspectjAopInterceptor.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
```

**Comment by qiujiayu** [comment]
按你的写法，我测了一下，没有问题。看你的错误应该是缓存key哪里有冲突了。我把查检冲突的代码加上了，你fork后，用源码调试一下你的代码。

**Comment by ming300** [comment]
详细跟踪了代码,发现了造成 `java.lang.ClassCastException: java.lang.ref.SoftReference cannot be cast to java.util.concurrent.ConcurrentHashMap` 的原因
原来的配置
```
 @Cache(expire =DateEx.SECOND_ONE_HOUR,
            autoload = false, key = "'SysUserServiceImpl_bypk'",
            hfield = "#args[0]", condition = "#args.length>0",
            exCache = {@ExCache(
                    expire =DateEx.SECOND_ONE_HOUR,
                    key = "'SysUserServiceImpl_byName'",
                    hfield = "#retVal.userName",condition="#retVal.userName!=null")})
    public ConsUser findByPk(String id) {
    }
```

但参数为null的时候,就容易产生 CCE 异常,因为 hfield 的值为null,但是 key 实际对于的对象却是map.

解决办法 ,调整condition表达式 为 `#args.length>0 and #args[0]!=null`

最终为:
```
 @Cache(expire =DateEx.SECOND_ONE_HOUR,
            autoload = false, key = "'SysUserServiceImpl_bypk'",
            hfield = "#args[0]", condition = "#args.length>0 and  #args[0]!=null",
            exCache = {@ExCache(
                    expire =DateEx.SECOND_ONE_HOUR,
                    key = "'SysUserServiceImpl_byName'",
                    hfield = "#retVal.userName",condition="#retVal.userName!=null")})
    public ConsUser findByPk(String id) {
    }
```
