### ISSUE TITLE
整合异常

### ISSUE THREAD

**Issue by zhengmingliang** [qiujiayu/AutoLoadCache#40]
我几乎完全按照使用文档配置使用的，但总是报`Caused by: com.jarvis.cache.exception.LoadDataTimeOutException`的错误，想问下是哪儿配置的出问题了么
```
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy60.queryByScheduleId(Unknown Source)
	at com.dtsz.scheduletask.service.impl.TriggerServiceImpl.queryByScheduleId(TriggerServiceImpl.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy70.queryByScheduleId(Unknown Source)
	at com.dtsz.scheduletask.controller.ScheduleController.queryTriggers(ScheduleController.java:518)
	at com.dtsz.scheduletask.controller.ScheduleController$$FastClassBySpringCGLIB$$f9d5bc5d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.dtsz.scheduletask.aspect.SystemLogAspect.doAround(SystemLogAspect.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
	at com.dtsz.scheduletask.controller.ScheduleController$$EnhancerBySpringCGLIB$$209b7631.queryTriggers(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.jarvis.cache.exception.LoadDataTimeOutException: cache for key "schedule:trigger_scheduleId42e93ea3e5c346a285d5a01ee5a3633d" loaded 1 times.
	at com.jarvis.cache.DataLoader.doWaitRequest(DataLoader.java:195)
	at com.jarvis.cache.DataLoader.loadData(DataLoader.java:116)
	at com.jarvis.cache.DataLoader.doWaitRequest(DataLoader.java:193)
	at com.jarvis.cache.DataLoader.loadData(DataLoader.java:116)
	at com.jarvis.cache.CacheHandler.proceed(CacheHandler.java:194)
	at com.jarvis.cache.aop.aspectj.AspectjAopInterceptor.proceed(AspectjAopInterceptor.java:69)
	at com.jarvis.cache.aop.aspectj.AspectjAopInterceptor.checkAndProceed(AspectjAopInterceptor.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:97)
	at com.jarvis.cache.aop.aspectj.AspectjCacheAopProxyChain.doProxyChain(AspectjCacheAopProxyChain.java:45)
	at com.jarvis.cache.DataLoader.getData(DataLoader.java:210)
	at com.jarvis.cache.DataLoader.doFirstRequest(DataLoader.java:150)
	at com.jarvis.cache.DataLoader.loadData(DataLoader.java:102)
	at com.jarvis.cache.CacheHandler.proceed(CacheHandler.java:194)
	at com.jarvis.cache.aop.aspectj.AspectjAopInterceptor.proceed(AspectjAopInterceptor.java:69)
	at com.jarvis.cache.aop.aspectj.AspectjAopInterceptor.checkAndProceed(AspectjAopInterceptor.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
```

**Comment by qiujiayu** [comment]
@Cache(waitTimeOut=500)

**Comment by zhengmingliang** [comment]
默认值就是500ms，我改成了5000ms还是这个问题

**Comment by zhengmingliang** [comment]
下面是配置信息
1. 这是mapper
```java

public interface TriggerMapper extends Mapper<TriggerEntity> {

    @Cache(expire=600, autoload=true, key="'trigger_scheduleId'+#args[0]",waitTimeOut = 5000)
    List<TriggerVO> queryByScheduleId(@Param("scheduleId") String scheduleId);
}
```
2. 这个配置文件

···xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-3.0.xsd">

    <bean id="autoLoadConfig" class="com.jarvis.cache.to.AutoLoadConfig">
        
        <property name="namespace" value="schedule"/>
        
        <property name="threadCnt" value="10"/>
        
        <property name="maxElement" value="20000"/>
        
        <property name="printSlowLog" value="true"/>
        
        <property name="slowLoadTime" value="500"/>
        
        <property name="sortType" value="1"/>
        
        <property name="checkFromCacheBeforeLoad" value="false"/>
        
        <property name="autoLoadPeriod" value="50"/>
        
        
        
        

        <property name="functions">
            <map>
                <entry key="isEmpty" value="com.jarvis.cache.CacheUtil" />
            </map>
        </property>
    </bean>


    
    
    <bean id="fastjsonSerializer" class="com.jarvis.cache.serializer.FastjsonSerializer"/>

    
    <bean id="springEl" class="com.jarvis.cache.script.SpringELParser"/>

    
    <bean id="jedisPoolConfig" class="redis.clients.jedis.JedisPoolConfig">
        <property name="maxTotal" value="200"/>
        <property name="maxIdle" value="100"/>
        <property name="minIdle" value="50"/>
        <property name="maxWaitMillis" value="10000"/>
        <property name="testOnBorrow" value="false"/>
        <property name="testOnReturn" value="false"/>
        <property name="testWhileIdle" value="true"/>
    </bean>

    <bean id="shardedJedisPool" class="redis.clients.jedis.ShardedJedisPool">
        <constructor-arg ref="jedisPoolConfig"/>
        <constructor-arg>
            <list>
                <bean class="redis.clients.jedis.JedisShardInfo">
                    <constructor-arg value="${redis1.host}"/>
                    <constructor-arg type="int" value="${redis1.port}"/>
                    
                </bean>
            </list>
        </constructor-arg>
    </bean>

    <bean id="cacheManager" class="com.jarvis.cache.redis.ShardedJedisCacheManager">
        <constructor-arg ref="fastjsonSerializer"/>
        <property name="shardedJedisPool" ref="shardedJedisPool"/>
    </bean>

    
    <bean id="cacheHandler" class="com.jarvis.cache.CacheHandler" destroy-method="destroy">
        <constructor-arg ref="cacheManager"/>
        <constructor-arg ref="springEl"/>
        <constructor-arg ref="autoLoadConfig"/>
        <constructor-arg ref="fastjsonSerializer"/>
    </bean>

    
    <bean id="cacheInterceptor" class="com.jarvis.cache.aop.aspectj.AspectjAopInterceptor">
        <constructor-arg ref="cacheHandler"/>
    </bean>

    
    
    <aop:config proxy-target-class="false">
        
        <aop:aspect ref="cacheInterceptor">
            <aop:pointcut id="daoCachePointcut"
                          expression="execution(public !void com.dtsz.scheduletask.dao..*.*(..))"/>
            <aop:around pointcut-ref="daoCachePointcut" method="checkAndProceed"/>
        </aop:aspect>

        
        <aop:aspect ref="cacheInterceptor"
                    order="1000">
            <aop:pointcut id="deleteCachePointcut"
                          expression="execution(* com.dtsz.scheduletask.dao..*.*(..))"/>
            <aop:after-returning pointcut-ref="deleteCachePointcut" method="checkAndDeleteCache"
                                 returning="retVal"/>
        </aop:aspect>

        
        
            
                          
            
        

    </aop:config>

    
    <aop:config proxy-target-class="false">
        
        <aop:aspect ref="cacheInterceptor">
            <aop:pointcut id="daoCachePointcut2"
                          expression="execution(public !void com.dtsz.scheduletask.service..*.*(..))"/>
            <aop:around pointcut-ref="daoCachePointcut" method="checkAndProceed"/>
        </aop:aspect>

        
        <aop:aspect ref="cacheInterceptor"
                    order="1000">
            <aop:pointcut id="deleteCachePointcut2"
                          expression="execution(* com.dtsz.scheduletask.service..*.*(..))"/>
            <aop:after-returning pointcut-ref="deleteCachePointcut" method="checkAndDeleteCache"
                                 returning="retVal"/>
        </aop:aspect>
    </aop:config>
</beans>
···

**Comment by qiujiayu** [comment]
你先把@Cache注释了，看看是不是耗时比较长。

**Comment by zhengmingliang** [comment]
哎，然而并没有……注释掉注解后，正常查询，查询时间几十毫秒

**Comment by qiujiayu** [comment]
你是不是mapper和service都加了@Cache注解？

**Comment by zhengmingliang** [comment]
是的，但是Service那个应该是没有起作用，我刚刚写了单元测试，只测试mapper，结果还是那样……

**Comment by qiujiayu** [comment]
把Service层的代码也贴出来看一下？

**Comment by qiujiayu** [comment]
或者到 QQ群：429274886 里沟通。

**Comment by zhengmingliang** [comment]
调试的时候，这一块就没打印AutoLoadCache的日志，当然了也没抛什么异常，主要是内层的Mapper已经异常了
![image](https://user-images.githubusercontent.com/16442564/32256168-6352369c-bee8-11e7-9c1e-ee7421b6f1b3.png)

**Comment by qiujiayu** [comment]
at com.jarvis.cache.DataLoader.doWaitRequest(DataLoader.java:195)
	at com.jarvis.cache.DataLoader.loadData(DataLoader.java:116)
	at com.jarvis.cache.DataLoader.doWaitRequest(DataLoader.java:193)
	at com.jarvis.cache.DataLoader.loadData(DataLoader.java:116)
	at com.jarvis.cache.CacheHandler.proceed(CacheHandler.java:194)
	at com.jarvis.cache.aop.aspectj.AspectjAopInterceptor.proceed(AspectjAopInterceptor.java:69)
	at com.jarvis.cache.aop.aspectj.AspectjAopInterceptor.checkAndProceed(AspectjAopInterceptor.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:97)
	at com.jarvis.cache.aop.aspectj.AspectjCacheAopProxyChain.doProxyChain(AspectjCacheAopProxyChain.java:45)
	at com.jarvis.cache.DataLoader.getData(DataLoader.java:210)
	at com.jarvis.cache.DataLoader.doFirstRequest(DataLoader.java:150)
	at com.jarvis.cache.DataLoader.loadData(DataLoader.java:102)
	at com.jarvis.cache.CacheHandler.proceed(CacheHandler.java:194)

从异常情况来看，应该同一个执行过程中，使用了相同的缓存key。
执行第一个@Cache注解方法 proceed--> loadData-->doFirstRequest-->getData-->执行第二个@Cache注解方法 proceed--> loadData ->doWaitRequest（这里变成doWaitRequest，说明已有请求在请求加载相同的数据）。

**Comment by zhengmingliang** [comment]
嗯，是的，我调试的时候，发现走了一次doFirstRequest两次doWaitRequest,去缓存里拿了四次数据……也是醉了……这是我写的单元测试，（另外，已加群）
![image](https://user-images.githubusercontent.com/16442564/32256240-ed01f148-bee8-11e7-93f6-74bf1739b024.png)

![1](https://user-images.githubusercontent.com/16442564/32256310-3fbc20ac-bee9-11e7-8257-3916d016aa4a.png)

**Comment by qiujiayu** [comment]
你mybatis有做什么特殊处理吗？

**Comment by zhengmingliang** [comment]
项目使用的是通用mapper（tk.mybatis.spring.mapper），我怀疑可能是冲突了，所以单元测试的时候就用的官方的mapper（org.mybatis.spring.mapper），一样的问题，我还发现文档中说`proxy-target-class=false为jdk代理，为true的话，会导致拦截不了mybatis的mapper `，我设置为true或者false都是一样的这个问题

**Comment by zhengmingliang** [comment]
这个是mybatis的配置文件，我把通用mapper的部分（含插件）注释掉,换成官方配置，也是这个问题，把注解去掉，可以正常查询到库中数据
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-4.3.xsd
		http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
		http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.3.xsd
		http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-4.3.xsd">

    <!-- 配置数据源 -->
    <bean name="dataSource" class="com.alibaba.druid.pool.DruidDataSource"
          init-method="init" destroy-method="close">
        <property name="url" value="${jdbc_url}"/>
        <property name="username" value="${jdbc_username}"/>
        <property name="password" value="${jdbc_password}"/>
        <!--<property name="driverClassName" value="${jdbc_driverClassName}"/>-->

        <!-- 初始化连接大小 -->
        <property name="initialSize" value="5"/>
        <!-- 连接池最大使用连接数量 -->
        <property name="maxActive" value="20"/>
        <!-- 连接池最大空闲 -->
        <!--<property name="maxIdle" value="20"/>-->
        <!-- 连接池最小空闲 -->
        <property name="minIdle" value="1"/>
        <!-- 获取连接最大等待时间 -->
        <property name="maxWait" value="60000"/>

        <!--如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false。-->
        <!-- 打开PSCache，并且指定每个连接上PSCache的大小 -->
        <property name="poolPreparedStatements" value="true"/>
        <property name="maxPoolPreparedStatementPerConnectionSize" value="30"/>

        <property name="validationQuery" value="${jdbc_validationQuery}"/>
        <property name="testOnBorrow" value="false"/>
        <property name="testOnReturn" value="false"/>
        <property name="testWhileIdle" value="true"/>

        <!-- 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 -->
        <property name="timeBetweenEvictionRunsMillis" value="60000"/>
        <!-- 配置一个连接在池中最小生存的时间，单位是毫秒 -->
        <property name="minEvictableIdleTimeMillis" value="1800000"/>

        <!-- 打开removeAbandoned功能 -->
        <property name="removeAbandoned" value="true"/>
        <!-- 1800秒，也就是30分钟 -->
        <property name="removeAbandonedTimeout" value="1800"/>
        <!-- 关闭abanded连接时输出错误日志 -->
        <property name="logAbandoned" value="true"/>

        <!-- 监控数据库 -->
        <!-- <property name="filters" value="stat" /> -->
        <property name="filters" value="mergeStat"/>
    </bean>


    <!-- myBatis文件 -->
    <bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
        <property name="dataSource" ref="dataSource"/>
        <!-- 自动扫描mapper目录, 省掉Configuration.xml里的手工配置 -->
        <property name="configLocation" value="classpath:spring/mybatis-config.xml"></property>
        <property name="mapperLocations" value="classpath*:com/dtsz/scheduletask/mapper/*.xml"/>
        <property name="plugins">
            <array>
                <!--PageHelper分页插件-->
                <bean class="com.github.pagehelper.PageInterceptor">

                    <property name="properties">
                        <value>
                            helperDialect=oracle
                            offsetAsPageNum=true
                            rowBoundsWithCount=true
                            pageSizeZero=true
                            reasonable=true
                            params=pageNum=pageNo
                        </value>
                    </property>
                </bean>

                <!-- 分页插件或其他插件，OrderBy 一定要在分页插件下面（主要是为了避免 count 也被增加排序） -->
                <!--<bean class="tk.mybatis.orderbyhelper.OrderByHelper"/>-->
            </array>

        </property>
    </bean>
    <!-- mybatis扫描配置 -->
    <bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
    <property name="basePackage" value="com.dtsz.scheduletask.dao" />
    <property name="sqlSessionFactoryBeanName" value="sqlSessionFactory" />
    </bean>
    <bean class="tk.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="basePackage" value="com.dtsz.scheduletask.dao"/>
        <!-- 3.2.2版本新特性，markerInterface可以起到mappers配置的作用，详细情况需要看Marker接口类 -->
        <property name="markerInterface" value="tk.mybatis.mapper.common.Mapper"/>
        <!-- 通用Mapper通过属性注入进行配置，默认不配置时会注册Mapper<T>接口

     -->
    </bean>

    <!-- 自动扫描(自动注入) -->
    <context:component-scan base-package="com.dtsz.scheduletask.service.impl"/>

    <bean id="sqlSession" class="org.mybatis.spring.SqlSessionTemplate" scope="prototype">
        <constructor-arg index="0" ref="sqlSessionFactory"/>
    </bean>
    <!-- 配置事务管理器 -->
    <bean id="transactionManager"
          class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
        <property name="dataSource" ref="dataSource"/>
    </bean>

    <!-- 注解方式配置事物 -->
    <!-- <tx:annotation-driven transaction-manager="transactionManager" /> -->

    <!-- 拦截器方式配置事物 -->
    <tx:advice id="transactionAdvice" transaction-manager="transactionManager">
        <tx:attributes>

            <tx:method name="insert*" propagation="REQUIRED"/>
            <tx:method name="batchInsert*" propagation="REQUIRED"/>
            <tx:method name="update*" propagation="REQUIRED"/>
            <tx:method name="batchUpdate*" propagation="REQUIRED"/>
            <tx:method name="delete*" propagation="REQUIRED"/>
            <tx:method name="batchDelete*" propagation="REQUIRED"/>

            <tx:method name="query*" read-only="true" propagation="SUPPORTS"/>
            <tx:method name="select*" read-only="true" propagation="SUPPORTS"/>

            <tx:method name="*" propagation="SUPPORTS"/>
        </tx:attributes>
    </tx:advice>
    <aop:config>
        <aop:pointcut id="transactionPointcut"
                      expression="execution(* com.dtsz.scheduletask.service.*.*(..))"/>
        <aop:advisor pointcut-ref="transactionPointcut"
                     advice-ref="transactionAdvice"/>
    </aop:config>


    <!-- 配置druid监控spring jdbc -->
    <bean id="druid-stat-interceptor"
          class="com.alibaba.druid.support.spring.stat.DruidStatInterceptor">
    </bean>
    <bean id="druid-stat-pointcut" class="org.springframework.aop.support.JdkRegexpMethodPointcut"
          scope="prototype">
        <property name="patterns">
            <list>
                <value>com.dtsz.scheduletask.service.*</value>
            </list>
        </property>
    </bean>


</beans>
```

**Comment by zhengmingliang** [comment]
这根redis的配置有关吗，我没有采用集群模式，暂时先用的单机的，单机redis也像文档中那么配置？？

**Comment by qiujiayu** [comment]
你可以把AutoloadCache的源码导入到你的eclipse中，然后
 com.jarvis.cache.aop.aspectj.AspectjAopInterceptor.checkAndProceed 打印些当类的一些信息：类名，类的类型等。
可以参考：https://github.com/qiujiayu/autoload-cache-spring-boot-starter/blob/master/src/main/java/com/jarvis/cache/interceptor/CacheMethodInterceptor.java

**Comment by qiujiayu** [comment]
我初步觉得是 tkMybatis也增加了一些代理功能，而我们这里没有做好判断处理造成的。

**Comment by zhengmingliang** [comment]
我单元测试的时候，把tk mybatis 的相应配置和插件已经注释掉了

**Comment by qiujiayu** [comment]
你先调试一下再看看吧。

**Comment by zhengmingliang** [comment]
恩恩，好的，十分感谢您抽出时间来帮忙查看问题

**Comment by qiujiayu** [comment]
https://github.com/abel533/MyBatis-Spring-Boot/issues/39

看看是不是同样的问题？

**Comment by zhengmingliang** [comment]
不是...
