### ISSUE TITLE
asm单元测试报错

### ISSUE THREAD

**Issue by lizanle521** [qiujiayu/AutoLoadCache#52]
Exception in thread "main" java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    com/jarvis/cache/aop/asm/Account$EnhancedByASM.<init>()V @5: aload_0
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab7 0008 b12a b700 0bb1               

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at com.jarvis.cache.aop.asm.SecureAccountGenerator.generateSecureAccount(SecureAccountGenerator.java:28)
	at com.jarvis.cache.aop.asm.AccountTest.main(AccountTest.java:11)

**Comment by qiujiayu** [comment]
使用jdk1.6测一下，就可以了
